### ISSUE TITLE
Getting error when merging

### ISSUE THREAD

**Issue by Hugo-Calero** [arcee-ai/PruneMe#13]
Hello!

I am trying out the code to prune mistral7b. I am able to compute the layer similarities, however, after updating the slice.yaml file accordingly, I receive the following error when running the merge_me.py file.

Error:
Traceback (most recent call last):
  File "/Users/hugocalero/Desktop/PruneMe/slice_with_mergekit/merge_me.py", line 18, in <module>
    run_merge(
  File "/Users/hugocalero/Desktop/PruneMe/slice_with_mergekit/mergekit/mergekit/merge.py", line 87, in run_merge
    ).plan_to_disk(out_path=out_path)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugocalero/Desktop/PruneMe/slice_with_mergekit/mergekit/mergekit/plan.py", line 259, in plan_to_disk
    self._plan()
  File "/Users/hugocalero/Desktop/PruneMe/slice_with_mergekit/mergekit/mergekit/plan.py", line 308, in _plan
    ConfigReader(
  File "/Users/hugocalero/Desktop/PruneMe/venv/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ConfigReader
config
  Input should be a valid dictionary or instance of MergeConfiguration [type=model_type, input_value=MergeConfiguration(merge_...te=None, out_dtype=None), input_type=MergeConfiguration]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type
    
    
    
 Has anyone experienced anything similar to this or knows how to solve it?
Any help would be greatly appreciated :)

**Comment by shamanez** [comment]
I guess the problem is with the Mergekit[ yaml loading method](https://github.com/arcee-ai/PruneMe/blob/main/slice_with_mergekit/merge_me.py#L16).

I used this notebook - https://github.com/arcee-ai/mergekit/blob/main/notebook.ipynb

Maybe try to install the correct pydantic version.

**Comment by Hugo-Calero** [comment]
Hello, thank you for your answer!

I checked and the pydantic version I have installed is 2.7.1

Any idea of what other version could make it work?

**Comment by shamanez** [comment]
Sorry I am not sure about it. Would be nice to ask this question from the Mergekit library .

**Comment by Hugo-Calero** [comment]
Okay, many thanks!
